---
abstract: 'Complex business rule data validation'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Brick
no_index:
  directory:
    - t
    - inc
requires:
  DateTime: 0.36
  File::MMagic: 0
  MIME::Types: 0
  Storable: 0
  Test::Data: 0
  Test::Manifest: 1.14
  Test::More: 0
  Test::Output: 0
version: 0.227
